read_pdf_task:
  description: >
    Using the path {pdf_path}, access the PDF file
    so that its text can be returned.
  expected_output: >
    Text extracted from the PDF file.
  agent: pdf_reader_agent

analyze_task:
  description: >
    Your purpose is to analyze the recieved text and determine whether
    information should be removed or not. You may remove redundant text,
    unecessary extra spaces and any text that deviates too much from the general text topic. 
    Really make sure you're not removing information that adds value to the general text.
  expected_output: >
    Text that contains only the most relevant parts of the original text, without unnecessary details.
  agent: analyzer_agent
  context: [read_pdf_task]

summarize_task:
  description: >
    Summarize the received text, using the specified ChatGPT model, in a way that keeps it cohesive. 
    If the text recieved isn't short already, be sure to compare it to the original text's size, 
    and then make it relatively shorter. 
  expected_output: >
    A relatively consise and accurate summmary generated from the recieved text. 
  agent: summarizer_agent
  context: [analyze_task]

format_task:
  description: >
    Format the given summary to match the style of a blog post.
  expected_output: >
    A Markdown-formatted text that includes a relevant title and subheadings to organize the content. 
    The text should be cohesive and clearly formatted.
  agent: formatter_agent
  context: [summarize_task]

quality_assurance_task:
  description: >
    Ensure that the quality of the produced blog post is clear and consistent with the original PDF.
  expected_output: >
    The final Markdown text after review. At the end, guarantee there is a line that signs off the text 
    like this: "Made by Ollama/Gpt."
  agent: quality_assurance_agent
  context: [format_task]
