read_pdf_task:
  description: >
    Using the path {pdf_path}, access the PDF file
    so that its text can be returned.
  expected_output: >
    Text extracted from the PDF file.
  agent: pdf_reader_agent

analyze_task:
  description: >
    Your purpose is to analyze the recieved text and determine whether
    information should be removed or not. You may remove redundant text,
    unecessary extra spaces and any text that deviates too much from the general text topic. 
    Really make sure you're not removing information that adds value to the general text.
  expected_output: >
    Text that contains only the most relevant parts of the original text, without unnecessary details.
  agent: analyzer_agent
  context: [read_pdf_task]

summarize_task:
  description: >
    Summarize the received text, using the specified ChatGPT model, in a way that keeps it cohesive. 
    If the text recieved isn't short already, be sure to compare it to the original text's size, 
    and then make it relatively shorter. 
  expected_output: >
    A relatively consise and accurate summmary generated from the recieved text. 
  agent: summarizer_agent
  context: [analyze_task]

format_task:
  description: >
    Format the given summary to match the style of a blog post.
  expected_output: >
    A Markdown-formatted text that has to include:
    - A relevant main title (always the first element of file);
    - Subheadings to organize all the content;
    - A conclusion. 
    The text should be cohesive and properly formatted according to Markdown standards. 
    At the end, guarantee there is a line that signs off the text 
    like this: "Made by Ollama/ChatGPT."
    After formatting it, revise your work to make sure it looks correct.
  agent: formatter_agent
  context: [summarize_task]

